// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp3ZZMr8AL8rtCAH5R-p_-aoHY_IKk1xg',
    appId: '1:1089624315833:web:1de6dea3d526f516b20868',
    messagingSenderId: '1089624315833',
    projectId: 'kit305tut5',
    authDomain: 'kit305tut5.firebaseapp.com',
    storageBucket: 'kit305tut5.appspot.com',
    measurementId: 'G-94TP6GK248',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTE-C8jGRUrtq2JUV8oHh9IZi976aWcys',
    appId: '1:1089624315833:android:d64556100cc887f6b20868',
    messagingSenderId: '1089624315833',
    projectId: 'kit305tut5',
    storageBucket: 'kit305tut5.appspot.com',
  );
}
